# Generated by Django 4.2.7 on 2023-11-03 10:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_blognews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, null=True, populate_from='tittle', unique=True),
        ),
    ]
