# Generated by Django 4.2.7 on 2023-11-03 10:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_blognews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='tittle', unique=True),
        ),
    ]
